force-app/main/default/objects/ATM_Fee__c/ATM_Fee__c.object-meta.xml
<CustomObject>
    <label>ATM Fee in other currencies</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>ATM Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATM Fees in other currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATM_Fee__c/fields/ATM_Fee_PK__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_PK__c</fullName>
    <label>ATM Fee PK</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ATM_Fee__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Products.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Products</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ATMFeeTriggerHandler.cls
/**
 * @author  Kevin Pujol
 * @version 1.0
 * @description Trigger Handler to handle the logic when a ATM Fee is created, updated or deleted
 */
public with sharing class ATMFeeTriggerHandler implements TriggerInterface{

    public ATMFeeTriggerHandler() {
    }

    public void bulkBefore() {
    }

    public void bulkAfter() {
    }

    public void beforeInsert(SObject so) {
        ATM_Fee__c fee = (ATM_Fee__c) so;
        fee.ATM_Fee_PK__c = fee.Product__c + fee.Home_Country__c;
    }

    public void beforeUpdate(SObject oldSo, SObject so) {
        ATM_Fee__c fee = (ATM_Fee__c) so;
        ATM_Fee__c oldFee = (ATM_Fee__c) oldSo;
        if(fee.Product__c != oldFee.Product__c || fee.Home_Country__c != oldFee.Home_Country__c){
            fee.ATM_Fee_PK__c = fee.Product__c + oldFee.Home_Country__c;
        }
    }

    public void beforeDelete(SObject so) {
    }

    public void afterInsert(SObject so) {
    }
    
    public void afterUpdate(SObject oldSo, SObject so) {
    }

    public void afterDelete(SObject so) {
    }
 
    public void andFinally() {
    }

}