force-app/main/default/objects/ATM_Fee__c/ATM_Fee__c.object-meta.xml
<CustomObject>
    <label>ATM Fee in other currencies</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>ATM Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATM Fees in other currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATM_Fee__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Cost__c/Monthly_Cost__c.object-meta.xml
<CustomObject>
    <label>Cost Per Calendar Month</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>Monthly Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs Per Calendar Month</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Cost__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Replacement_Cost__c/Replacement_Cost__c.object-meta.xml
<CustomObject>
    <label>Card Replacement Cost</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>Replacement Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Replacement Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Replacement_Cost__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Products.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Products</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductInformationHelper.cls
/**
 * @author  Kevin Pujol
 * @version 1.0
 * @description This class includes rehusable methods and classes for both the ProductInformationController and the ProductInformationRestService
 */
global with sharing class ProductInformationHelper {
    global static void populateProductInformation(ProductWrapper productInfo, Contact contact){
        //All the following fields are required, they will never be null.
        productInfo.productName = contact.Product__c;
        productInfo.countryName = contact.Home_Country__c;
        Monthly_Cost__c monthlyCost = ProductInformationRepository.getMonthlyCost(contact.Product__c, contact.Home_Country__c);
        productInfo.monthlyCost = monthlyCost == null ? null : monthlyCost.Value__c;
        ATM_Fee__c atmFee = ProductInformationRepository.getATMFee(contact.Product__c, contact.Home_Country__c);
        productInfo.atmFee = atmFee == null ? null : atmFee.Value__c;
        Replacement_Cost__c replacementCost = ProductInformationRepository.getReplacementCost(contact.Product__c, contact.Home_Country__c);
        productInfo.replacementCost = replacementCost == null ? null : replacementCost.Value__c;
    }

    global class ProductWrapper{
        @AuraEnabled public String productName {get;set;}
        @AuraEnabled public String countryName {get;set;}
        @AuraEnabled public String monthlyCost {get;set;}
        @AuraEnabled public String atmFee {get;set;}
        @AuraEnabled public String replacementCost {get;set;}
    }
}