force-app/main/default/objects/ATM_Fee__c/ATM_Fee__c.object-meta.xml
<CustomObject>
    <label>ATM Fee in other currencies</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>ATM Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATM Fees in other currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATM_Fee__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Contact External ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Cost__c/Monthly_Cost__c.object-meta.xml
<CustomObject>
    <label>Cost Per Calendar Month</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>Monthly Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs Per Calendar Month</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Cost__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Replacement_Cost__c/Replacement_Cost__c.object-meta.xml
<CustomObject>
    <label>Card Replacement Cost</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>Replacement Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Replacement Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Replacement_Cost__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Products.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Products</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductInformationRepository.cls
/**
 * @author  Kevin Pujol
 * @version 1.0
 * @description Data access layer for the Product Information LWC
 */
public with sharing class ProductInformationRepository {
    public static Contact getContactById (Id contactId){
        Contact contact = null;
        List<Contact> contacts = [SELECT Id, Product__c, Home_Country__c FROM Contact WHERE Id =: contactId];
        if(!contacts.isEmpty()){
            contact = contacts.get(0);
        }
        return contact;
    }

    public static Contact getContactByExternalId (String externalId){
        Contact contact = null;
        List<Contact> contacts = [SELECT Id, Product__c, Home_Country__c FROM Contact WHERE External_ID__c =: externalId];
        if(!contacts.isEmpty()){
            contact = contacts.get(0);
        }
        return contact;
    }

    public static List<Contact> getContactsByLastName (String lastName){
        List<Contact> contacts = new List<Contact>();
        return [SELECT Id FROM Contact WHERE LastName =: lastName];
    }

    public static Monthly_Cost__c getMonthlyCost (String product, String country){
        Monthly_Cost__c monthlyCost = null;
        List<Monthly_Cost__c> monthlyCosts = [SELECT Id, Value__c FROM Monthly_Cost__c WHERE Product__c =: product AND Home_Country__c =: country];
        if(!monthlyCosts.isEmpty()){
            monthlyCost = monthlyCosts.get(0);
        }
        return monthlyCost;
    }

    public static ATM_Fee__c getATMFee (String product, String country){
        ATM_Fee__c atmFee = null;
        List<ATM_Fee__c> atmFees = [SELECT Id, Value__c FROM ATM_Fee__c WHERE Product__c =: product AND Home_Country__c =: country];
        if(!atmFees.isEmpty()){
            atmFee = atmFees.get(0);
        }
        return atmFee;
    }

    public static Replacement_Cost__c getReplacementCost (String product, String country){
        Replacement_Cost__c replacementCost = null;
        List<Replacement_Cost__c> replacementCosts = [SELECT Id, Value__c FROM Replacement_Cost__c WHERE Product__c =: product AND Home_Country__c =: country];
        if(!replacementCosts.isEmpty()){
            replacementCost = replacementCosts.get(0);
        }
        return replacementCost;
    }
}