force-app/main/default/objects/ATM_Fee__c/ATM_Fee__c.object-meta.xml
<CustomObject>
    <label>ATM Fee in other currencies</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>ATM Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATM Fees in other currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATM_Fee__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Contact External ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Cost__c/Monthly_Cost__c.object-meta.xml
<CustomObject>
    <label>Cost Per Calendar Month</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>Monthly Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs Per Calendar Month</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Cost__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Replacement_Cost__c/Replacement_Cost__c.object-meta.xml
<CustomObject>
    <label>Card Replacement Cost</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>Replacement Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Replacement Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Replacement_Cost__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Products.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Products</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductInformationRestServiceTest.cls
/**
 * @author  Kevin Pujol
 * @version 1.0
 * @description Test class for the ProductInformationRestService
 */
@isTest
public with sharing class ProductInformationRestServiceTest {
    private static final String CONTACT_LAST_NAME = 'Andi';
    private static final String CONTACT_EXTERNAL_ID = '482625235';
    private static final String STANDARD_PRODUCT = 'Standard';
    private static final String BLACK_PRODUCT = 'Black';
    private static final String SPAIN = 'ES';
    
    @TestSetup public static void setUpData(){
        Contact contact = new Contact(
            LastName = CONTACT_LAST_NAME,
            Product__c = STANDARD_PRODUCT,
            Home_Country__c = SPAIN,
            External_ID__c = CONTACT_EXTERNAL_ID
        );
        insert contact;
        Case caseRecord = new Case(
            origin = Case.Origin.getDescribe().getPicklistValues().get(0).getValue(),
            status = 'New'
        );
        insert caseRecord;
        Monthly_Cost__c monthlyCost = new Monthly_Cost__c(
            Product__c = STANDARD_PRODUCT,
            Home_Country__c = SPAIN,
            Value__c = '€ 1'        
        );
        insert monthlyCost;
        ATM_Fee__c atmFee = new ATM_Fee__c(
            Product__c = STANDARD_PRODUCT,
            Home_Country__c = SPAIN,
            Value__c = '1%'        
        );
        insert atmFee;
        Replacement_Cost__c replacementCost = new Replacement_Cost__c(
            Product__c = STANDARD_PRODUCT,
            Home_Country__c = SPAIN,
            Value__c = '£ 1'        
        );
        insert replacementCost;
    }

    @isTest static void retriveCustomerProductInformation(){
        Test.startTest();
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/ProductInformation/'+CONTACT_EXTERNAL_ID; 
        request.httpMethod = 'GET';
        RestContext.request = request;
        ProductInformationHelper.ProductWrapper productInfo = ProductInformationRestService.getProductInformation();
        Test.stopTest();
        System.assertEquals('€ 1',productInfo.monthlyCost, 'The Cost per Calendar Month for this contact must be € 1');
        System.assertEquals('1%',productInfo.atmFee, 'The ATM Fee in other currencies for this contact must be 1%');
        System.assertEquals('£ 1',productInfo.replacementCost, 'The Cost per Card Replacement Cost for this contact must be £ 1');
    }

    @isTest static void retriveNullCustomerProductInformation(){
        Test.startTest();
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/ProductInformation/'+'1234'; 
        request.httpMethod = 'GET';
        RestContext.request = request;
        ProductInformationHelper.ProductWrapper productInfo = ProductInformationRestService.getProductInformation();
        Test.stopTest();
        System.assertEquals(null,productInfo,'The ProductInfo is null for the given External ID');
    }
}