force-app/main/default/objects/Monthly_Cost__c/Monthly_Cost__c.object-meta.xml
<CustomObject>
    <label>Cost Per Calendar Month</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>Monthly Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs Per Calendar Month</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Cost__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Cost__c/fields/Monthly_Cost_PK__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Cost_PK__c</fullName>
    <label>Monthly Cost PK</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MonthlyCostTriggerHandler.cls
/**
 * @author  Kevin Pujol
 * @version 1.0
 * @description Trigger Handler to handle the logic when a Monthly Cost is created, updated or deleted
 */
public with sharing class MonthlyCostTriggerHandler implements TriggerInterface{

    public MonthlyCostTriggerHandler() {
    }

    public void bulkBefore() {
    }

    public void bulkAfter() {
    }

    public void beforeInsert(SObject so) {
        Monthly_Cost__c cost = (Monthly_Cost__c) so;
        cost.Monthly_Cost_PK__c = cost.Product__c + cost.Home_Country__c;
    }

    public void beforeUpdate(SObject oldSo, SObject so) {
        Monthly_Cost__c cost = (Monthly_Cost__c) so;
        Monthly_Cost__c oldCost = (Monthly_Cost__c) oldSo;
        if(cost.Product__c != oldCost.Product__c || cost.Home_Country__c != oldCost.Home_Country__c){
            cost.Monthly_Cost_PK__c = cost.Product__c + cost.Home_Country__c;
        }
    }

    public void beforeDelete(SObject so) {
    }

    public void afterInsert(SObject so) {
    }
    
    public void afterUpdate(SObject oldSo, SObject so) {
    }

    public void afterDelete(SObject so) {
    }
 
    public void andFinally() {
    }

}